[workspace]
projects = [
    "Bitshuffle",
    "ChunkCodecCore",
    "ChunkCodecTests",
    "LibAec",
    "LibBlosc",
    "LibBlosc2",
    "LibBrotli",
    "LibBzip2",
    "LibLz4",
    "LibLzma",
    "LibSnappy",
    "LibZlib",
    "LibZstd",
]
